In [1]:
%cd ../../../

/Users/hoangle/Projects/untangling-people/Food-Waste-Optimization

In [2]:
import re
import sys
from itertools import zip_longest

import numpy as np
import pandas as pd
from loguru import logger

In [3]:
logger.remove()
logger.add(sys.stdout, level="DEBUG")

1

# Add meals

In [4]:
def hamming_distance(s1: str, s2: str) -> float:
    min_len = min(len(s1), len(s2))
    dist = sum(c1 != c2 for c1, c2 in zip_longest(s1, s2))  * 1.0 / min_len

    return dist

In [5]:
meals = {}

map_mealname2id = {}

## Process meal list

In [6]:
meals_raw = pd.read_excel("data/processed/phase_4/menus.xlsx", sheet_name="meals")

meals_raw.head()

   meal_code                                       meal_name category   CO2
0       34.0  Sitruunaiset kalapaloja ja kukkakaalitsatsikia     kala  0.81
1      710.0                         Broileri-Caesarsalaatti     kana  0.67
2      724.0                              Broilerilasagnette     kana  0.82
3      725.0               Broilerinuggetit, currykastiketta     kana  1.06
4      726.0                  Broileripyörykät, currykastike     kana  0.86

In [7]:
# Remove duplicate entries
meal_list = (
    meals_raw
    .dropna(axis=0, how='any')
    .drop(columns='CO2')
    .groupby('meal_code')
    .last()
    .reset_index()
    .rename(columns={
        'meal_code': 'meal_id',
        'meal_name': 'meal',
        'category': 'meal_type',
    })
)


# Decompose meal name and tag
pat1 = r"(\s?\(\s?[A-Z](\w|\,|\s)*\))"
pat2 = r"(\(|\)|\s)"

def _f_extract_tag(s: str):
    meal_name, tag = "", ""

    s = s.strip()
    out = re.findall(pat1, s)
    if len(out) < 1:
        meal_name = s
    else:
        meal_name = re.sub(pat1, "", s).strip()
        tag = out[0][0]
        tag = re.sub(pat2, '', tag)

    return pd.Series({'meal': meal_name, 'tag': tag})
    
meal_list['meal'] = meal_list['meal'].str.strip().apply(_f_extract_tag)['meal']
meal_list = meal_list.groupby('meal').first().reset_index()


meal_list['meal_type'] = meal_list['meal_type'].str.strip().map({
    'kala': 'fish',
    'liha': 'meat',
    'kana': 'chicken',
    'vegaani': 'vegan',
    'kasvis': 'vegetarian',
    'keskiarvo': 'buffet',
})

meal_list['meal_id'] = meal_list['meal_id'].astype(int)

meal_list = meal_list.sort_values('meal_id').groupby('meal').first().reset_index()

meal_list = meal_list[~meal_list['meal'].str.lower().str.contains('take away')]

meal_list['schoolyear'] = "23-24"


meal_list.head()

                                       meal  meal_id   meal_type schoolyear
0            "Butter" härkäpapua & pähkinää     9017       vegan      23-24
1              2023 Härkäpu-sienilasagnette     7201       vegan      23-24
2           Appelisiini-luomukikhernecurrya     9032       vegan      23-24
3  Artisokkavugetteja & tuoretomaattisalsaa     9102       vegan      23-24
4             Aurajuusto-pinaattilasagnette     7010  vegetarian      23-24

### Add meals in `meal_list` to dict `meals`

In [8]:
THRES = 0.1

for meal_other in meal_list.itertuples():
    if meal_other.meal in meals:    # exact match
        # With meal_list, we dont care exact match case
        logger.debug("here 1")
    else:
        # Find approximate match
        meal_id_best = None
        dist_best = 1e10
        for meal_name, meal_id in map_mealname2id.items():
            dist = hamming_distance(meal_other.meal, meal_name)

            if dist <= THRES and dist < dist_best:
                dist_best = dist
                meal_id_best = meal_id

        # Handle 2 cases: found approximate match and not found
        if meal_id_best is None:   # not found
            meals[meal_other.meal_id] = {
                'meal_type': meal_other.meal_type,
                'schoolyear': meal_other.schoolyear,
                'restaurant': None,
                'attributes': []
            }

            map_mealname2id[meal_other.meal] = meal_other.meal_id
        else:                   # found approximate match
            logger.debug(f"herer 2: {meal_other.meal_id} - {meal_id_best}")

            map_mealname2id[meal_other.meal] = meal_id_best

2025-01-30 12:40:19.712 | DEBUG    | __main__:<module>:29 - herer 2: 3656 - 6356
2025-01-30 12:40:19.752 | DEBUG    | __main__:<module>:29 - herer 2: 1125 - 6963
2025-01-30 12:40:19.882 | DEBUG    | __main__:<module>:29 - herer 2: 6045 - 6044

# Merge meals in menu to `meals`

## Process menu file

In [9]:
path = "data/processed/phase_4/menus.xlsx"

weeks = ["week1", "week2", "week3", "week4", "week5", "week6"]

list_menus = []
for week in weeks:
    raw = pd.read_excel(path, sheet_name=week)

    list_menus.append(raw)

menus_raw = pd.concat(list_menus)
menus_raw.head()

,meal_id,meal_name,meal_type,is_kela,is_gluten_free,is_new,is_vegan
0,7609,"Lohta pesto & mustajuurta (L, G)",today's special,False,True,False,False
1,7607,"Broileria pekonikastikkeessa (L, G, KELA)",today's special,True,True,False,False
2,9039,BBQ-savutofuburger & raikasta nektariiniketsup...,today's special,False,False,True,False
3,6121,"Karamellisoitua possua (M,G,KELA)",today's special,True,True,False,False
4,6818,Filippiiniläiset kanavartaat & Hedelmäsalsaa (...,today's special,True,True,False,False

In [10]:
menus = menus_raw.copy()

# Decompose meal name and tag
pat1 = r"(\s?\(\s?[A-Z](\w|\,|\s)*\))"
pat2 = r"(\(|\)|\s)"

def _f_extract_tag(s: str):
    meal_name, tag = "", ""

    s = s.strip()
    out = re.findall(pat1, s)
    if len(out) < 1:
        meal_name = s
    else:
        meal_name = re.sub(pat1, "", s).strip()
        tag = out[0][0]
        tag = re.sub(pat2, '', tag)

    return pd.Series({
        'meal': meal_name,
        'tag': tag
    })
    
menus['meal_name'] = menus['meal_name'].apply(_f_extract_tag)['meal']

# Process meal_id
pat_meal_code = r"(\d*)\s*\/\s*(\d*)"

def _f_extract_meal_id(s):
    match s:
        case int():
            meal_id = s
        case str():
            meal_id = int(s.split('/')[0])

    return meal_id

menus['meal_id'] = menus['meal_id'].apply(_f_extract_meal_id)

# Remove duplicate meals
menus = menus.groupby('meal_id').first().reset_index()

# Row-wise processing 
meal_type_che_exac = ['fish', 'meat', 'today’s special', 'vegan-kpl', 'vegan-miscellaneous']
meal_type_phy = ['salad', 'baguettes']

def _f_process_row(row) -> pd.Series:
    out = {
        'meal_type': None,
        'schoolyear': None,
        'restaurant': None,
        'attributes': [],
    }

    # schoolyear
    out['schoolyear'] = '24-25'

    # meal_type
    meal_type = row.meal_type.strip()
    if meal_type in ['meat', 'fish']:
        out['meal_type'] = meal_type
    else:
        out['attributes'].append(meal_type)
    if row.is_vegan:
        out['meal_type'] = "vegan"

    # restaurant
    if meal_type in meal_type_che_exac:
        out['restaurant'] = 'che-exa-vik'
    elif meal_type in meal_type_phy:
        out['restaurant'] = 'phy'

    # other attributes
    if row.is_kela:
        out['attributes'].append("kela")
    if row.is_gluten_free:
        out['attributes'].append("gluten_free")

    return pd.Series(out)
processed = menus.apply(_f_process_row, axis=1)
menus = pd.concat(
    [
        menus[['meal_id', 'meal_name']],
        processed
    ],
    axis=1
)

menus.head()

,meal_id,meal_name,meal_type,schoolyear,restaurant,attributes
0,710,Broileri-Caesarsalaatti,None,24-25,phy,"[salad, kela]"
1,785,Meksikolainen uunimakkara,meat,24-25,che-exa-vik,"[kela, gluten_free]"
2,790,Uunimakkara ja sinappikastike,meat,24-25,che-exa-vik,"[kela, gluten_free]"
3,791,Carbonara-kastike & pastaa,meat,24-25,che-exa-vik,[gluten_free]
4,839,Chili-katkarapusalaatti,None,24-25,phy,"[salad, kela, gluten_free]"

### Compose list of baguettes

In [11]:
baguettes_raw = pd.read_excel("data/processed/phase_4/menus.xlsx", sheet_name="baguettes")

baguettes_raw.head()

   meal_id                          meal meal_type   co2  is_kela
0     1445         Lounaspatonki, juusto    kasvis  0.79    False
1     1446  Lounaspatonki, kalkkunatahna      kana  0.53    False
2     1447         Lounaspatonki, kasvis   vegaani  0.35     True
3     1448      Lounaspatonki, katkarapu      kala  1.04     True
4     1449         Lounaspatonki, kinkku      liha  0.46    False

In [12]:
baguettes = baguettes_raw.copy()


# Remove unnecessary columns
baguettes.drop(columns='co2', inplace=True)

# Rename meal_type
baguettes['meal_type'] = baguettes['meal_type'].map({
    'kasvis': 'vegetarian',
    'kana': 'chicken',
    'vegaani': 'vegan',
    'kala': 'fish',
    'liha': 'meat'
})
baguettes['meal_name'] = baguettes['meal'].str.strip()


# Add other columns
baguettes['restaurant'] = 'phy'

baguettes['schoolyear'] = '24-25'

baguettes['attributes'] = baguettes['is_kela'].apply(lambda x: ['baguettes', 'kela'] if x else ['baguettes'])

# Remove redundant columns
baguettes = baguettes.drop(columns=['is_kela', 'meal'])

baguettes.head()

,meal_id,meal_type,meal_name,restaurant,schoolyear,attributes
0,1445,vegetarian,"Lounaspatonki, juusto",phy,24-25,[baguettes]
1,1446,chicken,"Lounaspatonki, kalkkunatahna",phy,24-25,[baguettes]
2,1447,vegan,"Lounaspatonki, kasvis",phy,24-25,"[baguettes, kela]"
3,1448,fish,"Lounaspatonki, katkarapu",phy,24-25,"[baguettes, kela]"
4,1449,meat,"Lounaspatonki, kinkku",phy,24-25,[baguettes]

In [13]:
menus = pd.concat([menus, baguettes], ignore_index=True)

menus.head()

,meal_id,meal_name,meal_type,schoolyear,restaurant,attributes
0,710,Broileri-Caesarsalaatti,None,24-25,phy,"[salad, kela]"
1,785,Meksikolainen uunimakkara,meat,24-25,che-exa-vik,"[kela, gluten_free]"
2,790,Uunimakkara ja sinappikastike,meat,24-25,che-exa-vik,"[kela, gluten_free]"
3,791,Carbonara-kastike & pastaa,meat,24-25,che-exa-vik,[gluten_free]
4,839,Chili-katkarapusalaatti,None,24-25,phy,"[salad, kela, gluten_free]"

## Merge `meals` with 2024-2025 menu

In [14]:
def coalesce(*args):
    for x in args:
        if x:
            return x
    return None

for meal in menus.itertuples():
    if meal.meal_id in meals:       # Look up with `meal_id` and found
        meal_info = meals[meal.meal_id]

        # # Handle corner case: 2 meals have same meal_id but different meal_
        map_mealname2id[meal.meal_name] = meal.meal_id
        
        meal_info['meal_type'] = coalesce(meal.meal_type, meal_info['meal_type'])
        meal_info['schoolyear'] = coalesce(meal.schoolyear, meal_info['schoolyear'])
        meal_info['restaurant'] = meal.restaurant
        meal_info['attributes'] = meal.attributes
    else:                           # Not found -> Look up with `meal_name` using Hamming distance
        # Closest meal in terms of Hamming distance is one having smallest distance and that distance is smaller than threshold
        best_meal = None
        best_dist = 1e10

        for name, meal_id in map_mealname2id.items():
            dist = hamming_distance(meal.meal_name, name)
            
            if dist <= THRES and dist < best_dist:
                best_dist = dist
                best_meal = name

        if best_meal:
            # Found meal having similar meal name -> Update meal info
            logger.debug(f"{meal.meal_name} ({meal.meal_id}) - {best_meal}")

            meal_info = meals[map_mealname2id[best_meal]]

            meal_info['meal_type'] = coalesce(meal.meal_type, meal_info['meal_type'])
            meal_info['schoolyear'] = coalesce(meal.schoolyear, meal_info['schoolyear'])
            meal_info['restaurant'] = meal.restaurant
            meal_info['attributes'] = meal.attributes

            map_mealname2id[meal.meal_name] = map_mealname2id[best_meal]
        else:
            # No found similar meal -> Add new meal
            logger.debug(f"New: {meal.meal_name}")

            map_mealname2id[meal.meal_name] = meal.meal_id
            meals[meal.meal_id] = {
                'meal_type': meal.meal_type,
                'schoolyear': meal.schoolyear,
                'restaurant': meal.restaurant,
                'attributes': meal.attributes,
            }

2025-01-30 12:40:20.341 | DEBUG    | __main__:<module>:32 - Mustajuurikeitto (1125) - Mustajuurikeitto
2025-01-30 12:40:20.344 | DEBUG    | __main__:<module>:32 - Kasviskorma (7202) - Kasviskorma
2025-01-30 12:40:20.357 | DEBUG    | __main__:<module>:32 - TexMex-siemenpyöryköitä ja Louisana-kastiketta (8983) - TexMex-siemenpyöryköitä ja Louisana-kastikett
2025-01-30 12:40:20.371 | DEBUG    | __main__:<module>:32 - Marokkolaiset kasvispihvit & Chermoula kastiketta (8985) - Marokkolaiset kasvispihvit & Chermoula kastik
2025-01-30 12:40:20.377 | DEBUG    | __main__:<module>:32 - Peas of Heaven chorizokeitto (8986) - Peas of Heaven chorizokeitto
2025-01-30 12:40:20.381 | DEBUG    | __main__:<module>:32 - Täysjyväkalafileetä & lime-korianteriremouladea (8988) - Täysjyväkalafileetä & lime-korianteriremoulad
2025-01-30 12:40:20.383 | DEBUG    | __main__:<module>:32 - Rapeaa ruiskalaa & piparjuurikastiketta (8989) - Rapeaa ruiskalaa & piparjuurikastiketta
2025-01-30 12:40:20.385 | DEBUG    | __main__:<module>:44 - New: Seifileetä piparjuuri-kermakastikkeessa
2025-01-30 12:40:20.387 | DEBUG    | __main__:<module>:32 - Hapankorppukuorrutettua uuniseifileetä (8992) - Hapankorppukuorrutettua uuniseifileetä
2025-01-30 12:40:20.390 | DEBUG    | __main__:<module>:44 - New: Munakoiso-luomukikhernetaginea & basilikakastiketta
2025-01-30 12:40:20.392 | DEBUG    | __main__:<module>:32 - Lihaton keitto (8994) - Lihaton keitto
2025-01-30 12:40:20.394 | DEBUG    | __main__:<module>:32 - Libanonilainen ratatouille (8997) - Libanonilainen ratatouille
2025-01-30 12:40:20.396 | DEBUG    | __main__:<module>:32 - Satay Nyhtis Bowl (20003) - Satay Nyhtis Bowl
2025-01-30 12:40:20.398 | DEBUG    | __main__:<module>:32 - Lounaspatonki, savu-nyhtökaura (3656) - Lounaspatonki, savu-nyhtökaura

# Merge with meals from POS

## Process POS files

In [15]:
paths = [
    "data/raw/pos/Sold lunches.csv",
    "data/raw/pos/Sold lunches Kumpula 6-8 2024.csv",
    "data/raw/pos/Sold lunches Kumpula 9-10 2024.csv",
    "data/raw/pos/Sold lunches Viikuna 2023.csv",
    "data/raw/pos/Sold lunches Viikuna 2024.csv"
]

raw = []
for path in paths:
    df = pd.read_csv(path, delimiter=';')
    df.columns = np.arange(df.shape[1])
    raw.append(df)


pos_raw = pd.concat(raw, ignore_index=True)
pos_raw.head()

/var/folders/pr/8dv_cj95295bxt_hr8hzrmk40000gn/T/ipykernel_45957/1467303410.py:11: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, delimiter=';')

,0,1,2,3,4,5,6
0,2.1.2023,10:31,600 Chemicum,Liha,"Uunimakkaraa,sinappikastiketta",1,"0,9"
1,2.1.2023,10:32,600 Chemicum,Kala,Kalapuikot tillikermaviilikast,1,"1,04"
2,2.1.2023,10:32,600 Chemicum,Liha,"Uunimakkaraa,sinappikastiketta",1,"0,9"
3,2.1.2023,10:35,600 Chemicum,Kala,Kalapuikot tillikermaviilikast,1,"1,04"
4,2.1.2023,10:36,600 Chemicum,Liha,"Uunimakkaraa,sinappikastiketta",2,"1,8"

In [16]:
pos = pos_raw.copy()


# Rename columns
pos.columns = np.arange(pos.shape[1])
pos.rename(
    columns={
        0: 'date',
        1: 'time',
        2: 'restaurant',
        3: 'meal_type',
        4: 'meal',
        5: 'pcs',
        6: 'co2',
    },
    inplace=True
)


# Process date
pos['date'] = pd.to_datetime(pos['date'], format="%d.%m.%Y")



# Process meal_type
pos['meal_type'] = pos['meal_type'].map({
    'Liha': 'meat',
    'Kala': 'fish',
    'Vegaani': 'vegan',
    'Kasvis': 'vegetarian',
    'Kana': 'chicken'
})


# Process meal
pos['meal'] = pos['meal'].str.strip()


# Map restaurant name
pos['restaurant'] = pos['restaurant'].map({
    '600 Chemicum': 'che-exa-vik', #'chemicum',
    '610 Physicum': 'phy', #'physicum',
    '620 Exactum': 'che-exa-vik', #'exactum'
    '570 Viikuna': 'che-exa-vik',
})


# Get pair of meal and meal_type
meals_pos = pos.groupby(['meal', 'meal_type']).last().reset_index()


# Extract schoolyear
meals_pos['schoolyear'] = meals_pos['date'].apply(lambda x: '24-25' if x >= pd.to_datetime("2024-09-01") else '23-24')


# Keep necessary columns
meals_pos = meals_pos[['meal', 'meal_type', 'restaurant', 'schoolyear']]


# Remove take away
meals_pos = meals_pos[~meals_pos['meal'].str.lower().str.contains('take away')]
meals_pos.rename(columns={'meal': 'meal_name'}, inplace=True)



meals_pos.head()

                          meal_name   meal_type   restaurant schoolyear
0  "Butter" luomukikhernekastiketta       vegan  che-exa-vik      24-25
1    Aurajuusto-pinaattilasagnettea  vegetarian  che-exa-vik      24-25
2            BBQ-Broilerikastiketta     chicken  che-exa-vik      24-25
3      Bangladeshilainen linssipata       vegan  che-exa-vik      23-24
4          Bar Myöhä Bbq-seitanbowl       vegan  che-exa-vik      24-25

In [17]:
meals_pos[meals_pos['meal_name'] == 'Panini, hot chili kana']

                  meal_name meal_type restaurant schoolyear
260  Panini, hot chili kana   chicken        phy      24-25

## Merge meals from POS data with `meals`

In [18]:
THRES = 0.1

for meal_other in meals_pos.itertuples():
    # Find exact match via name
    if meal_other.meal_name in map_mealname2id:
        meal = meals[map_mealname2id[meal_other.meal_name]]

        meal['meal_type'] = coalesce(meal_other.meal_type, meal['meal_type'])
        meal['schoolyear'] = max(meal['schoolyear'], meal_other.schoolyear)
        meal['restaurant'] = coalesce(meal['restaurant'], meal_other.restaurant)

        continue
    

    # Find approximate match
    best_meal = None
    best_dist = 1e10
    
    for name, meal_id in map_mealname2id.items():
        dist = hamming_distance(meal_other.meal_name, name)
        
        if dist <= THRES and dist < best_dist:
            best_dist = dist
            best_meal = name

    # Handle 2 cases: found approximate match and not found
    if best_meal is None:
        # Not found similar meal -> Add new meal
        logger.debug(f"New: {meal_other.meal_name}")

        meal_id = max(max(meals.keys()), 90_000_000) + 1
        map_mealname2id[meal_other.meal_name] = meal_id
        meals[meal_id] = {
            'meal_type': meal_other.meal_type,
            'schoolyear': meal_other.schoolyear,
            'restaurant': meal_other.restaurant,
            'attributes': []
        }
    else:
        # Found meal having similar meal name -> Update meal info
        logger.debug(f"Approximate: {meal_other.meal_name} - {best_meal}")

        meal_info = meals[map_mealname2id[best_meal]]

        meal_info['meal_type'] = coalesce(meal_other.meal_type, meal_info['meal_type'])
        meal_info['schoolyear'] = coalesce(meal_other.schoolyear, meal_info['schoolyear'])
        meal_info['restaurant'] = meal_other.restaurant


        map_mealname2id[meal_other.meal_name] = map_mealname2id[best_meal]

2025-01-30 12:40:20.945 | DEBUG    | __main__:<module>:41 - Approximate: Aurajuusto-pinaattilasagnettea - Aurajuusto-pinaattilasagnette
2025-01-30 12:40:20.948 | DEBUG    | __main__:<module>:41 - Approximate: BBQ-Broilerikastiketta - BBQ-broilerikastiketta
2025-01-30 12:40:20.950 | DEBUG    | __main__:<module>:29 - New: Bangladeshilainen linssipata
2025-01-30 12:40:20.952 | DEBUG    | __main__:<module>:29 - New: Bataattipihvit BBQ-tomaattik.
2025-01-30 12:40:20.954 | DEBUG    | __main__:<module>:29 - New: Bataattipihvit,curry-minttukas
2025-01-30 12:40:20.956 | DEBUG    | __main__:<module>:41 - Approximate: Bataattipihvit,curry-minttusoi - Bataattipihvit,curry-minttukas
2025-01-30 12:40:20.958 | DEBUG    | __main__:<module>:29 - New: BeanItStroganoff
2025-01-30 12:40:20.961 | DEBUG    | __main__:<module>:29 - New: Broileri-nacho-salaattia
2025-01-30 12:40:20.963 | DEBUG    | __main__:<module>:29 - New: Broilerinfileetä vuohenjuustok
2025-01-30 12:40:20.965 | DEBUG    | __main__:<module>:29 - New: Broilerinkoipea, currykastiket
2025-01-30 12:40:20.967 | DEBUG    | __main__:<module>:29 - New: Broilerinuggetit, madraskastik
2025-01-30 12:40:20.969 | DEBUG    | __main__:<module>:29 - New: Broilerkastiketta Tikka Masala
2025-01-30 12:40:20.975 | DEBUG    | __main__:<module>:29 - New: Broilernug ja Red curry-mangka
2025-01-30 12:40:20.990 | DEBUG    | __main__:<module>:41 - Approximate: Butter Chicken - Butter chicken
2025-01-30 12:40:20.997 | DEBUG    | __main__:<module>:29 - New: Butterhärkäpapua
2025-01-30 12:40:20.999 | DEBUG    | __main__:<module>:41 - Approximate: Chili con Peas of Heaven - Chili con peas of heaven
2025-01-30 12:40:21.002 | DEBUG    | __main__:<module>:41 - Approximate: Chili con nyhtis - Chili con Nyhtis
2025-01-30 12:40:21.006 | DEBUG    | __main__:<module>:29 - New: Chorizo lihap ja papcoulinsia
2025-01-30 12:40:21.008 | DEBUG    | __main__:<module>:29 - New: Chorizo lihap ja ruskkastike
2025-01-30 12:40:21.010 | DEBUG    | __main__:<module>:29 - New: Falafel-pitaleipä
2025-01-30 12:40:21.012 | DEBUG    | __main__:<module>:29 - New: Falafel-pyörykät, tzaziki jogu
2025-01-30 12:40:21.014 | DEBUG    | __main__:<module>:29 - New: Falafelpihvejä & paahdettua valkosipuli
2025-01-30 12:40:21.016 | DEBUG    | __main__:<module>:29 - New: Falafelpyörykät, tzazikisoijaj
2025-01-30 12:40:21.019 | DEBUG    | __main__:<module>:29 - New: Falafelpyörylöitä & makean tulista paprikamajoa
2025-01-30 12:40:21.021 | DEBUG    | __main__:<module>:29 - New: Fermentoitua härkäpapua tomaatti
2025-01-30 12:40:21.023 | DEBUG    | __main__:<module>:29 - New: Feta-kirsikkatom peltilaatikko
2025-01-30 12:40:21.025 | DEBUG    | __main__:<module>:29 - New: Filip. kanavart. & hedelmsalsa
2025-01-30 12:40:21.034 | DEBUG    | __main__:<module>:29 - New: Grillattu kana ohutleipärulla
2025-01-30 12:40:21.037 | DEBUG    | __main__:<module>:29 - New: Gruusialaista kaalilaatikkoa
2025-01-30 12:40:21.039 | DEBUG    | __main__:<module>:29 - New: Haukipyöryköitä, sitr.kastike
2025-01-30 12:40:21.041 | DEBUG    | __main__:<module>:41 - Approximate: Herkkulohipihvit, punajuurimaj - Herkkulohipihvit, punajuurimajon
2025-01-30 12:40:21.043 | DEBUG    | __main__:<module>:41 - Approximate: Herkkusienikeittoa - Herkkusienikeitto
2025-01-30 12:40:21.045 | DEBUG    | __main__:<module>:29 - New: Hernekeitto ja laskiaispulla
2025-01-30 12:40:21.047 | DEBUG    | __main__:<module>:29 - New: Hlö Savukalasalaatti
2025-01-30 12:40:21.048 | DEBUG    | __main__:<module>:29 - New: Huli Huli Broil, Gochujangmajo
2025-01-30 12:40:21.050 | DEBUG    | __main__:<module>:29 - New: Härkäpapubolognaise
2025-01-30 12:40:21.052 | DEBUG    | __main__:<module>:29 - New: Härkäpu-sienilasagnette
2025-01-30 12:40:21.054 | DEBUG    | __main__:<module>:29 - New: Intialaista linssikeittoa
2025-01-30 12:40:21.056 | DEBUG    | __main__:<module>:29 - New: Intialaista linssimuhennosta
2025-01-30 12:40:21.058 | DEBUG    | __main__:<module>:29 - New: Italialaisia kasvispyöryköitä
2025-01-30 12:40:21.061 | DEBUG    | __main__:<module>:29 - New: Italialaisia kasvispyöryköitä & Gremolatadippiä
2025-01-30 12:40:21.062 | DEBUG    | __main__:<module>:41 - Approximate: Jambalayaa & paahdettua halloumia - Jambalayaa & paahdettua Halloumia
2025-01-30 12:40:21.064 | DEBUG    | __main__:<module>:29 - New: Joululounas, kinkulla
2025-01-30 12:40:21.066 | DEBUG    | __main__:<module>:29 - New: Joululounas, punajuuripihvit
2025-01-30 12:40:21.068 | DEBUG    | __main__:<module>:41 - Approximate: Juuressosekeittoa - Juuressosekeitto
2025-01-30 12:40:21.071 | DEBUG    | __main__:<module>:29 - New: Kaalilaatikkoa gruusialaisittain ja puolukkasurvos
2025-01-30 12:40:21.073 | DEBUG    | __main__:<module>:29 - New: Kalajuurespihvit, ruohosipulik
2025-01-30 12:40:21.075 | DEBUG    | __main__:<module>:29 - New: Kalapuikot tillikermaviilikast
2025-01-30 12:40:21.077 | DEBUG    | __main__:<module>:29 - New: Kalapuikot, sitruunakastiketta
2025-01-30 12:40:21.078 | DEBUG    | __main__:<module>:29 - New: Kalapyörykät, sitruunakermavii
2025-01-30 12:40:21.081 | DEBUG    | __main__:<module>:41 - Approximate: Kalkkunaa & bataattia BBQ-kastikkeella - Kalkkunaa & bataattia BBQ-kastikkeessa
2025-01-30 12:40:21.083 | DEBUG    | __main__:<module>:41 - Approximate: Kana-mascarpone lasagne - Kana-Mascarpone lasagne
2025-01-30 12:40:21.085 | DEBUG    | __main__:<module>:29 - New: Kanakebabia tomaattikastikeessa
2025-01-30 12:40:21.087 | DEBUG    | __main__:<module>:29 - New: Kanakepakot ja arrabiattakasti
2025-01-30 12:40:21.088 | DEBUG    | __main__:<module>:29 - New: Kanan koipi-reisi
2025-01-30 12:40:21.090 | DEBUG    | __main__:<module>:29 - New: Kanapyörykät,BBQ-kastike
2025-01-30 12:40:21.092 | DEBUG    | __main__:<module>:29 - New: Karibian kasvispihvi,mango-cur
2025-01-30 12:40:21.094 | DEBUG    | __main__:<module>:29 - New: Kasvis-jalapnuget ja tomatsals
2025-01-30 12:40:21.096 | DEBUG    | __main__:<module>:29 - New: Kasvis-jalopenonuggettit,limek
2025-01-30 12:40:21.098 | DEBUG    | __main__:<module>:29 - New: Kasvisjalapenonugetteja ja tomaatti-jalapenosalsaa
2025-01-30 12:40:21.100 | DEBUG    | __main__:<module>:29 - New: Kasvisjauhis.pih ja aprik.kast
2025-01-30 12:40:21.103 | DEBUG    | __main__:<module>:29 - New: Kasvisjauhispihvejä & valkosipuli-seesamdippiä
2025-01-30 12:40:21.105 | DEBUG    | __main__:<module>:29 - New: Kasvisjauhispihvit, aprikoosim
2025-01-30 12:40:21.107 | DEBUG    | __main__:<module>:29 - New: Kasvisjauhispyörykät,pippurika
2025-01-30 12:40:21.109 | DEBUG    | __main__:<module>:29 - New: Kasvisjauhispyörykät,tomaattik
2025-01-30 12:40:21.111 | DEBUG    | __main__:<module>:29 - New: Kasvisjauhispyöryköitä ja pippurikastiketta
2025-01-30 12:40:21.113 | DEBUG    | __main__:<module>:29 - New: Kasviskepukat, myskikurpitsadippi
2025-01-30 12:40:21.115 | DEBUG    | __main__:<module>:29 - New: Kasvispihvit Marokko,minttuker
2025-01-30 12:40:21.117 | DEBUG    | __main__:<module>:29 - New: Kasvispizza
2025-01-30 12:40:21.119 | DEBUG    | __main__:<module>:29 - New: Kauraleivitetty silakkapihvejä
2025-01-30 12:40:21.121 | DEBUG    | __main__:<module>:29 - New: Kievin kana,valkosipulikermav
2025-01-30 12:40:21.123 | DEBUG    | __main__:<module>:41 - Approximate: Kikherne-pähkinäpataa - Kikherne-pähkinäpata
2025-01-30 12:40:21.125 | DEBUG    | __main__:<module>:29 - New: Kikhernepan kalapal ja tacojog
2025-01-30 12:40:21.127 | DEBUG    | __main__:<module>:29 - New: Kikhernetagine, soijajogurttia
2025-01-30 12:40:21.129 | DEBUG    | __main__:<module>:29 - New: Kikhernetaginea & basilikasoijajogurttia
2025-01-30 12:40:21.131 | DEBUG    | __main__:<module>:29 - New: Kikhernetaginea& syysomenajogurttia
2025-01-30 12:40:21.133 | DEBUG    | __main__:<module>:29 - New: Kinkku-ananas-sinihomejpizza
2025-01-30 12:40:21.135 | DEBUG    | __main__:<module>:29 - New: Kinkku-aura ohutleipärulla
2025-01-30 12:40:21.137 | DEBUG    | __main__:<module>:29 - New: Kinkkukiusausta
2025-01-30 12:40:21.142 | DEBUG    | __main__:<module>:29 - New: Kirjolohipihvit, pinaattiakast
2025-01-30 12:40:21.152 | DEBUG    | __main__:<module>:29 - New: Kirjolohipyör ja palsternakjog
2025-01-30 12:40:21.157 | DEBUG    | __main__:<module>:29 - New: Kirjolohipyörykät,sitr.kermav.
2025-01-30 12:40:21.164 | DEBUG    | __main__:<module>:29 - New: Kirsikkatomaat-linssilasagnett
2025-01-30 12:40:21.166 | DEBUG    | __main__:<module>:29 - New: Kreikkalainen tomaattikeitto, vegaaninen
2025-01-30 12:40:21.169 | DEBUG    | __main__:<module>:29 - New: Kreikkalaista pinaattilasagnea
2025-01-30 12:40:21.172 | DEBUG    | __main__:<module>:29 - New: Kultakuorrepyörykät,savupapr.
2025-01-30 12:40:21.175 | DEBUG    | __main__:<module>:29 - New: Kultakuorrepyöryköitä & miedon tulista
2025-01-30 12:40:21.177 | DEBUG    | __main__:<module>:29 - New: Kvinoa pyöryk ja verigreipjogu
2025-01-30 12:40:21.179 | DEBUG    | __main__:<module>:29 - New: Kvinoa pyöryköitä & paprikamajoneesia
2025-01-30 12:40:21.181 | DEBUG    | __main__:<module>:29 - New: Lemoncurd-siemenkuorutettu lohi, Limekermaviili
2025-01-30 12:40:21.183 | DEBUG    | __main__:<module>:29 - New: Lihamakaronilaatikko (broileri)
2025-01-30 12:40:21.185 | DEBUG    | __main__:<module>:29 - New: Lihapulla Mac &cheese
2025-01-30 12:40:21.187 | DEBUG    | __main__:<module>:29 - New: Lihapullia tomaattikastikkeessa
2025-01-30 12:40:21.189 | DEBUG    | __main__:<module>:29 - New: Lime-persiljkal ja Was-ruckast
2025-01-30 12:40:21.191 | DEBUG    | __main__:<module>:41 - Approximate: Linssibolognesea - Linssibolognese
2025-01-30 12:40:21.193 | DEBUG    | __main__:<module>:29 - New: Linssimuhennosta
2025-01-30 12:40:21.195 | DEBUG    | __main__:<module>:29 - New: Linssishakshuks
2025-01-30 12:40:21.197 | DEBUG    | __main__:<module>:29 - New: Lohipuikko,lime-inkivääri
2025-01-30 12:40:21.199 | DEBUG    | __main__:<module>:29 - New: Lohipyöryköitä
2025-01-30 12:40:21.201 | DEBUG    | __main__:<module>:29 - New: Luomuhernekeittoa ja pannukak
2025-01-30 12:40:21.203 | DEBUG    | __main__:<module>:29 - New: Maapähkinä-kasvissosekeittoa
2025-01-30 12:40:21.205 | DEBUG    | __main__:<module>:29 - New: Makkara stroganoff
2025-01-30 12:40:21.208 | DEBUG    | __main__:<module>:41 - Approximate: Marokkolaiset kasvispihvit & Chermoula-kastiketta - Marokkolaiset kasvispihvit & Chermoula kastiketta
2025-01-30 12:40:21.210 | DEBUG    | __main__:<module>:41 - Approximate: Meksikolainen nyhtökaurasalaat - Meksikolainen nyhtökaurasalaatti
2025-01-30 12:40:21.212 | DEBUG    | __main__:<module>:29 - New: Meksikolaista broileria
2025-01-30 12:40:21.214 | DEBUG    | __main__:<module>:29 - New: Meksikolaista uunimakkaraa
2025-01-30 12:40:21.216 | DEBUG    | __main__:<module>:41 - Approximate: Meksikon Beanit Chilipata - Meksikon Beanit chilipata
2025-01-30 12:40:21.218 | DEBUG    | __main__:<module>:29 - New: Mosambikilainen pähk-papupata
2025-01-30 12:40:21.220 | DEBUG    | __main__:<module>:29 - New: Nacho-Härkispeltilaatikko
2025-01-30 12:40:21.222 | DEBUG    | __main__:<module>:29 - New: Nyhtökaura-makaronilaatikko
2025-01-30 12:40:21.224 | DEBUG    | __main__:<module>:41 - Approximate: Nyhtökaura-makaronilaatikkoa - Nyhtökaura-makaronilaatikko
2025-01-30 12:40:21.226 | DEBUG    | __main__:<module>:41 - Approximate: Paahdettu kikherne-tahinisalaa - Paahdettu kikherne-tahinisalaatti
2025-01-30 12:40:21.228 | DEBUG    | __main__:<module>:29 - New: Paist.muikkuja & remouladekast
2025-01-30 12:40:21.230 | DEBUG    | __main__:<module>:29 - New: Paneroid kalap ja Red currykas
2025-01-30 12:40:21.232 | DEBUG    | __main__:<module>:29 - New: Paneroidut kalapihvit,tartar
2025-01-30 12:40:21.234 | DEBUG    | __main__:<module>:29 - New: Paneroitu lohipihvi, sitruunak
2025-01-30 12:40:21.236 | DEBUG    | __main__:<module>:29 - New: Pannupizza,kinkku-ananas
2025-01-30 12:40:21.238 | DEBUG    | __main__:<module>:29 - New: Parmesan broileria,lime-dippik
2025-01-30 12:40:21.240 | DEBUG    | __main__:<module>:29 - New: Pasta Carbonara
2025-01-30 12:40:21.242 | DEBUG    | __main__:<module>:41 - Approximate: Peas of heaven chorizo -pataa - Peas of heaven chorizo  pataa
2025-01-30 12:40:21.244 | DEBUG    | __main__:<module>:41 - Approximate: Pesto-kasvislasagnea - Pesto-kasvislasagne
2025-01-30 12:40:21.246 | DEBUG    | __main__:<module>:29 - New: Pinaattikeitto, 1/2 kananmuna
2025-01-30 12:40:21.249 | DEBUG    | __main__:<module>:29 - New: Piparj-parmelohi, Herpiparjkas
2025-01-30 12:40:21.251 | DEBUG    | __main__:<module>:29 - New: Piparjilohi, Wakam+hernepipaka
2025-01-30 12:40:21.253 | DEBUG    | __main__:<module>:41 - Approximate: Pippurinen mascarponejuusto-kalkkunapata - Pippurinen Mascarponejuusto-kalkkunapata
2025-01-30 12:40:21.255 | DEBUG    | __main__:<module>:41 - Approximate: Porkkana-fenkolikeitto - Porkkana-Fenkolikeitto
2025-01-30 12:40:21.257 | DEBUG    | __main__:<module>:29 - New: Porkkanasosekeittoa,pestokerma
2025-01-30 12:40:21.260 | DEBUG    | __main__:<module>:29 - New: Porsaanleike,metsäsienikastike
2025-01-30 12:40:21.261 | DEBUG    | __main__:<module>:29 - New: Porsaanleikettä rosepippurikas
2025-01-30 12:40:21.263 | DEBUG    | __main__:<module>:29 - New: Possun poskea sinappikastikkeessa
2025-01-30 12:40:21.266 | DEBUG    | __main__:<module>:29 - New: Punajlinssipata ja kauradippi
2025-01-30 12:40:21.268 | DEBUG    | __main__:<module>:29 - New: Punajuuripihvejä,soijajogurtti
2025-01-30 12:40:21.270 | DEBUG    | __main__:<module>:29 - New: Punajuuripyörykät,soijajogurt
2025-01-30 12:40:21.273 | DEBUG    | __main__:<module>:41 - Approximate: Punajuuripyöryköitä ja tanskalaista remouladea - Punajuuripyöryköitä ja Tanskalaista remouladea
2025-01-30 12:40:21.275 | DEBUG    | __main__:<module>:29 - New: Pyttipannua, paistettu muna
2025-01-30 12:40:21.277 | DEBUG    | __main__:<module>:41 - Approximate: Pähkinäistä Feta-pinaattikastiketta - Pähkinäistä feta-pinaattikastiketta
2025-01-30 12:40:21.279 | DEBUG    | __main__:<module>:29 - New: Rapea Meiramikana
2025-01-30 12:40:21.281 | DEBUG    | __main__:<module>:29 - New: Rapea kalaleike, verigreipjogu
2025-01-30 12:40:21.283 | DEBUG    | __main__:<module>:29 - New: Rapea ruiskalafilee ja vihreää mojo-kermaviiliä
2025-01-30 12:40:21.286 | DEBUG    | __main__:<module>:29 - New: Rapeat kalapalat,tartarkastike
2025-01-30 12:40:21.288 | DEBUG    | __main__:<module>:41 - Approximate: Rapeita pinaattipuikkoja ja Ananas-salsaa - Rapeita pinaattipuikkoja ja ananas-salsaa
2025-01-30 12:40:21.291 | DEBUG    | __main__:<module>:41 - Approximate: Rapeita pinaattipuikkoja ja tulista Harissa dippiä - Rapeita pinaattipuikkoja ja tulista Harissa-dippiä
2025-01-30 12:40:21.293 | DEBUG    | __main__:<module>:29 - New: Ratatouille Uunifeta-harissa
2025-01-30 12:40:21.295 | DEBUG    | __main__:<module>:41 - Approximate: Red curry kalkkunaa - Red Curry kalkkunaa
2025-01-30 12:40:21.297 | DEBUG    | __main__:<module>:29 - New: Salaatti+proteiini
2025-01-30 12:40:21.299 | DEBUG    | __main__:<module>:29 - New: Savukirjolohikiusaus
2025-01-30 12:40:21.301 | DEBUG    | __main__:<module>:29 - New: Savustettua lohta ja limedippi
2025-01-30 12:40:21.303 | DEBUG    | __main__:<module>:29 - New: Savustettua lohta, tartar
2025-01-30 12:40:21.305 | DEBUG    | __main__:<module>:29 - New: Seesambroilerinfileetä, chilik
2025-01-30 12:40:21.307 | DEBUG    | __main__:<module>:29 - New: Seipyörykät ja hernepiparjkast
2025-01-30 12:40:21.310 | DEBUG    | __main__:<module>:41 - Approximate: Seitanpannu ja rakuunakastik. - Seitanpannu ja rakuunakastike
2025-01-30 12:40:21.312 | DEBUG    | __main__:<module>:29 - New: Sitruunaiset kalaleik& mojo-kermaviilikastike
2025-01-30 12:40:21.314 | DEBUG    | __main__:<module>:29 - New: Sitruunaiset kalapalat,tillika
2025-01-30 12:40:21.317 | DEBUG    | __main__:<module>:29 - New: Sitruunaisia kalaleikkeitä & nam jim -jogurttia
2025-01-30 12:40:21.320 | DEBUG    | __main__:<module>:29 - New: Sitruunaisia kalapaloja & Nam Jim jogurttia
2025-01-30 12:40:21.322 | DEBUG    | __main__:<module>:29 - New: Soijaa ja bataattia BBQ-kastik
2025-01-30 12:40:21.324 | DEBUG    | __main__:<module>:29 - New: Sveitsinleike
2025-01-30 12:40:21.327 | DEBUG    | __main__:<module>:41 - Approximate: Tattari-kaalilaatikkoa & hillottua puolukka - tattari-kaalilaatikkoa & hillottua puolukkaa
2025-01-30 12:40:21.329 | DEBUG    | __main__:<module>:29 - New: Tempura kalapaloja&Appelsiini-remouladea
2025-01-30 12:40:21.331 | DEBUG    | __main__:<module>:29 - New: Tempuraturskapaloja & appelsiini
2025-01-30 12:40:21.333 | DEBUG    | __main__:<module>:41 - Approximate: Teriyaki paahdettua kassleria - Teriyaki-paahdettua kassleria
2025-01-30 12:40:21.336 | DEBUG    | __main__:<module>:29 - New: TexMex-siemenpyöryköitä salsakastikkeessa
2025-01-30 12:40:21.339 | DEBUG    | __main__:<module>:29 - New: Tilli-katkaraputäytteistä kalaa&Thousand
2025-01-30 12:40:21.341 | DEBUG    | __main__:<module>:29 - New: Tofu-wokkia
2025-01-30 12:40:21.343 | DEBUG    | __main__:<module>:29 - New: Tofua ja pinaattia Palak P.
2025-01-30 12:40:21.345 | DEBUG    | __main__:<module>:41 - Approximate: Tofuratatouillea - Tofuratatouille
2025-01-30 12:40:21.347 | DEBUG    | __main__:<module>:29 - New: Tomaat tuorejuusto-tonnikalaka
2025-01-30 12:40:21.349 | DEBUG    | __main__:<module>:29 - New: Tomaat. kana-tuorejuustokast.
2025-01-30 12:40:21.352 | DEBUG    | __main__:<module>:29 - New: Tomaatti-mozzarellapizza
2025-01-30 12:40:21.354 | DEBUG    | __main__:<module>:29 - New: Tomaattikeittoa raejuustolla
2025-01-30 12:40:21.361 | DEBUG    | __main__:<module>:29 - New: Tomaattinen broilerkastike
2025-01-30 12:40:21.372 | DEBUG    | __main__:<module>:29 - New: Tomaattinen kvinoa-mustap
2025-01-30 12:40:21.379 | DEBUG    | __main__:<module>:29 - New: Tomaattista tonnikalakastikett
2025-01-30 12:40:21.382 | DEBUG    | __main__:<module>:29 - New: Tonnikala-pastavuoka
2025-01-30 12:40:21.386 | DEBUG    | __main__:<module>:41 - Approximate: Täyteläinen & tomaattinen Härkäpapupastavuoka - Täyteläinen & tomaattinen Härkäpapupastavuok
2025-01-30 12:40:21.388 | DEBUG    | __main__:<module>:29 - New: Uunimakkaraa,sinappikastiketta
2025-01-30 12:40:21.390 | DEBUG    | __main__:<module>:29 - New: Vebabia Tomaatti-basilikakast.
2025-01-30 12:40:21.393 | DEBUG    | __main__:<module>:29 - New: Vegaaninen Appelisiinicurry
2025-01-30 12:40:21.395 | DEBUG    | __main__:<module>:29 - New: Vegaaninen Luomutofu Biryani
2025-01-30 12:40:21.397 | DEBUG    | __main__:<module>:29 - New: Vegaaninen buttertofu
2025-01-30 12:40:21.399 | DEBUG    | __main__:<module>:29 - New: Vegaaninen makaronilaatikko
2025-01-30 12:40:21.401 | DEBUG    | __main__:<module>:41 - Approximate: Vege Rendang - Vege-Rendang
2025-01-30 12:40:21.404 | DEBUG    | __main__:<module>:29 - New: Vegejauhispyöryköitä & sipulikastiketta
2025-01-30 12:40:21.406 | DEBUG    | __main__:<module>:29 - New: Vegesuik, bataattia ja BBQ kas
2025-01-30 12:40:21.408 | DEBUG    | __main__:<module>:41 - Approximate: Vuohenjuusto-tomaattikeittoa - Vuohenjuusto-tomaattikeitto
2025-01-30 12:40:21.410 | DEBUG    | __main__:<module>:41 - Approximate: Vuohenjuustosalaattia - Vuohenjuustosalaatti
2025-01-30 12:40:21.412 | DEBUG    | __main__:<module>:29 - New: Välimerellinen  Beanit kastike

# Finalize `meals`

## Post-process `meals`

In [19]:
# Add `aliases`
for name, meal_id in map_mealname2id.items():
    if 'aliases' not in meals[meal_id]:
        meals[meal_id]['aliases'] = [name]
    else:
        meals[meal_id]['aliases'].append(name)



# Add `panini` to `attributes`
for name, meal_id in map_mealname2id.items():
    if 'panini' in name.lower():
        meals[meal_id]['attributes'].append('panini')

        logger.debug(f"panini: {meal_id}")


# Replace `restaurant`
for meal in meals.values():
    match (meal['restaurant']):
        case 'che-exa-vik':
            meal['restaurant'] = ['che', 'exa', 'vik']
        case 'phy':
            meal['restaurant'] = ['phy']


# Manually modify cases
del meals[6867]
del meals[6554]


df_meals = pd.DataFrame.from_dict(meals, orient='index').reset_index().rename(columns={'index': 'meal_id'})
df_meals.head()

2025-01-30 12:40:21.418 | DEBUG    | __main__:<module>:15 - panini: 6638
2025-01-30 12:40:21.418 | DEBUG    | __main__:<module>:15 - panini: 3524
2025-01-30 12:40:21.419 | DEBUG    | __main__:<module>:15 - panini: 3525
2025-01-30 12:40:21.419 | DEBUG    | __main__:<module>:15 - panini: 1513
2025-01-30 12:40:21.419 | DEBUG    | __main__:<module>:15 - panini: 1509
2025-01-30 12:40:21.419 | DEBUG    | __main__:<module>:15 - panini: 3211
2025-01-30 12:40:21.420 | DEBUG    | __main__:<module>:15 - panini: 4343
2025-01-30 12:40:21.420 | DEBUG    | __main__:<module>:15 - panini: 2906
2025-01-30 12:40:21.420 | DEBUG    | __main__:<module>:15 - panini: 1510
2025-01-30 12:40:21.420 | DEBUG    | __main__:<module>:15 - panini: 1512
2025-01-30 12:40:21.421 | DEBUG    | __main__:<module>:15 - panini: 6636
2025-01-30 12:40:21.421 | DEBUG    | __main__:<module>:15 - panini: 6096
2025-01-30 12:40:21.422 | DEBUG    | __main__:<module>:15 - panini: 1515
2025-01-30 12:40:21.422 | DEBUG    | __main__:<module>:15 - panini: 1516

,meal_id,meal_type,schoolyear,restaurant,attributes,aliases
0,9017,vegan,24-25,"[che, exa, vik]","[vegan-miscellaneous, kela]","[""Butter"" härkäpapua & pähkinää]"
1,7201,vegan,23-24,None,[],[2023 Härkäpu-sienilasagnette]
2,9032,vegan,23-24,None,[],[Appelisiini-luomukikhernecurrya]
3,9102,vegan,23-24,None,[],[Artisokkavugetteja & tuoretomaattisalsaa]
4,7010,vegetarian,24-25,"[che, exa, vik]",[],"[Aurajuusto-pinaattilasagnette, Aurajuusto-pin..."

## Unit tests

### Assert `map_mealname2id` contains all names

In [20]:
aliases = []
for alias in df_meals['aliases']:
    aliases.extend(alias)
aliases = set(aliases)

assert len(set(meals_pos['meal_name']).difference(aliases)) == 0
assert len(set(meal_list['meal']).difference(aliases)) == 0
assert len(set(menus['meal_name']).difference(aliases)) == 0

### Check `meal_type` in specific values

In [21]:
assert set(df_meals['meal_type'].unique()) == {'buffet', 'chicken', 'fish', 'meat', 'vegan', 'vegetarian'}

# Save dim

In [22]:
df_meals.to_parquet("data/processed/phase_4/dim_meals.parquet")